set encoding=UTF-8
set autoread
syntax enable
set t_Co=256
set nowrap
set background=dark
hi! Normal ctermbg=NONE guibg=NONE
set guifont=Hack\ Droid\ Sans\ Mono\ for\ Powerline\ Nerd\ Font\ Complete:h14
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set number
set nocursorline
set nocursorcolumn
syntax sync minlines=256
set wildmenu
set hidden
set cmdheight=1
set langmap=ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕHГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;`qwertyuiop[]asdfghjkl\\;'zxcvbnm\\,.~QWERTYUIOP{}ASDFGHJKL:\\"ZXCVBNM<>
set nocompatible
set backspace=indent,eol,start
let g:mapleader=','
set noerrorbells
set novisualbell
set noswapfile
set nobackup
set splitright
set splitbelow
set fileformats=unix,dos,mac
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
map <Space> :noh<cr>
set timeoutlen=1000
set ttimeoutlen=50
set list listchars=tab:→\ ,trail:·
